{{- if .Values.loki.gateway.route.enabled -}}
{{- $route := .Values.loki.gateway.route }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: {{ $route.kind | default "HTTPRoute" }}
metadata:
  name: {{ include "loki.gatewayFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) . | nindent 4 }}
  {{- end }}
  rules:
    {{- if $route.additionalRules }}
    {{- tpl (toYaml $route.additionalRules) . | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ include "loki.gatewayFullname" . }}
          port: 80
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- if and $route.securityPolicy $route.securityPolicy.enabled }}
{{- $policy := $route.securityPolicy }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "loki.gatewayFullname" . }}
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
    {{- with $policy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $policy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: {{ $route.kind | default "HTTPRoute" }}
      name: {{ $route.name | default (include "loki.gatewayFullname" . ) }}
  {{- with $policy.basicAuth }}
  basicAuth:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with $policy.cors }}
  cors:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with $policy.jwt }}
  jwt:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with $policy.oidc }}
  oidc:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with $policy.extAuth }}
  extAuth:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  {{- with $policy.authorization }}
  authorization:
    {{- toYaml . | nindent 4 }}
  {{ end }}
{{ end }}

{{- if and $route.backendTrafficPolicy $route.backendTrafficPolicy.enabled }}
{{ $trafficPolicy := $route.backendTrafficPolicy }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
    {{- with $trafficPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $trafficPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "loki.gatewayFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: {{ $route.kind | default "HTTPRoute" }}
    name: {{ $route.name | default (include "loki.gatewayFullname" . ) }}
  timeout:
    tcp:
      connectTimeout: {{ $trafficPolicy.timeout.tcp.connectTimeout | default "60s" }}
{{- end }}

{{- if and $route.httpRouteFilter $route.httpRouteFilter.enabled }}
{{ $filter := $route.httpRouteFilter }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
    {{- with $filter.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $filter.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "loki.gatewayFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with $filter.directResponse }}
  directResponse:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
