checks:	
  addAllBuiltIn: true	
  exclude:	
  - "use-namespace"
  - "unset-memory-requirements"
  - "unset-cpu-requirements"
  - "run-as-non-root"
  - "required-label-owner"
  - "required-annotation-email"
  - "non-isolated-pod"
  - "no-readiness-probe"
  - "no-read-only-root-fs"
  - "no-liveness-probe"
  - "default-service-account"
  - "no-rolling-update-strategy"
  - "read-secret-from-env-var"
  - "minimum-three-replicas"
  - "access-to-secrets"
  - "access-to-create-pods"
  - "dangling-service"
